x-build-common: &build-common
  context: .
  dockerfile: Dockerfile
  target: dev

x-env-common: &env-common
  JWT_SECRET: ${JWT_SECRET}
  DB_HOST: mysql-db
  DB_PORT: 3306
  DB_USER: ${MYSQL_DB_USERNAME}
  DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  REDIS_HOST: redis-stack
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  EUREKA_SERVER_HOST: eureka-server
  EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
  SPRING_DEVTOOLS_RESTART_ENABLED: true
  MAVEN_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

x-depends-common: &depends-common
  mysql-db:
    condition: service_healthy
  eureka-server:
    condition: service_started
  redis-stack:
    condition: service_started

x-libraries-common: &libraries-common
  path: ./UtilityResource/src
  action: sync+restart
  target: /app/UtilityResource/src

services:
  eureka-server:
    build:
      <<: *build-common
      args:
        MODULE_NAME: ServiceDiscovery
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./ServiceDiscovery/src
          action: sync+restart
          target: /app/ServiceDiscovery/src
        - path: ./ServiceDiscovery/pom.xml
          action: rebuild
        - *libraries-common

  api-gateway:
    build:
      <<: *build-common
      args:
        MODULE_NAME: ApiGateway
    ports:
      - "9010:9010"
    environment:
      <<: *env-common
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./ApiGateway/src
          action: sync+restart
          target: /app/ApiGateway/src
        - path: ./ApiGateway/pom.xml
          action: rebuild
        - *libraries-common

  user-service:
    build:
      <<: *build-common
      args:
        MODULE_NAME: UserService
    ports:
      - "9012:9012"
      - "5006:5005"
    environment:
      <<: *env-common
      DB_NAME: pos_user_service
    depends_on: *depends-common
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./UserService/src
          action: sync+restart
          target: /app/UserService/src
        - path: ./UserService/pom.xml
          action: rebuild
        - *libraries-common

  auth-service:
    build:
      <<: *build-common
      args:
        MODULE_NAME: AuthService
    ports:
      - "9013:9013"
      - "5005:5005"
    environment:
      <<: *env-common
      DB_NAME: pos_auth_service
    depends_on: *depends-common
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./AuthService/src
          action: sync+restart
          target: /app/AuthService/src
        - path: ./AuthService/pom.xml
          action: rebuild
        - *libraries-common

  store-service:
    build:
      <<: *build-common
      args:
        MODULE_NAME: StoreService
    ports:
      - "9014:9014"
      - "5007:5005"
    environment:
      <<: *env-common
      DB_NAME: pos_store_service
    depends_on: *depends-common
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./StoreService/src
          action: sync+restart
          target: /app/StoreService/src
        - path: ./StoreService/pom.xml
          action: rebuild
        - *libraries-common

  product-service:
    build:
      <<: *build-common
      args:
        MODULE_NAME: ProductService
    ports:
      - "9015:9015"
      - "5008:5005"
    environment:
      <<: *env-common
      DB_NAME: pos_product_service
    depends_on: *depends-common
    networks:
      - microservice-network
    develop:
      watch:
        - path: ./ProductService/src
          action: sync+restart
          target: /app/ProductService/src
        - path: ./ProductService/pom.xml
          action: rebuild
        - *libraries-common

  mysql-db:
    image: "mysql:8.4"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    volumes:
      - microservice-mysql:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${MYSQL_DB_USERNAME}", "-p${MYSQL_DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres-db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - microservice-network
    volumes:
      - microservice-postgres:/var/lib/postgresql/data

  pgAdmin:
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "superpass"
    depends_on:
      - postgres-db
    networks:
      - microservice-network

  redis-stack:
    image: "redis/redis-stack:latest"
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    networks:
      - microservice-network
    volumes:
      - microservice-redis:/data

networks:
  microservice-network:
    driver: bridge

volumes:
  microservice-postgres:
  microservice-mysql:
  microservice-redis: