server:
  port: 9013

spring:
#  config:
#    import: optional:file:.env[.properties]

  application:
    name: AuthService

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pos_auth}
    username: ${DB_USER:root}
    password:  ${DB_PASSWORD:RootPass!@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        format_sql: true
        ddl-auto: none

  jwt:
    secretKey: ${JWT_SECRET:54bwtwwUrbE9+Z4/4bjNPEEm71e+pYKuhEpS4XidXQc=}
    accessTokenExpiration: 900 # 5 M
    refreshTokenExpiration: 604800 # 7 Day

  main:
    banner-mode: off

  mail:
    from: test@mailtrap.io
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: bf968ba3e3defe
    password: 0c573e65e4d90f
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/